Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/belka/Library/Python/3.10/lib/python/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
area_district = ...


#Ð¡Ð¼Ð¾Ñ‚Ñ€Ð¸Ð¼ Ð½Ð° Ñ€ÐµÐ·ÑƒÐ»ÑŒÑ‚Ð°Ñ‚
print(f"ÐŸÐ»Ð¾Ñ‰Ð°Ð´ÑŒ Ñ€Ð°Ð¹Ð¾Ð½Ð°: {area_district[0]} Ð¼Â²")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 5[0m
[1;32m      1[0m area_district [38;5;241m=[39m [38;5;241m.[39m[38;5;241m.[39m[38;5;241m.[39m
[1;32m      4[0m [38;5;66;03m#Ð¡Ð¼Ð¾Ñ‚Ñ€Ð¸Ð¼ Ð½Ð° Ñ€ÐµÐ·ÑƒÐ»ÑŒÑ‚Ð°Ñ‚[39;00m
[0;32m----> 5[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mÐŸÐ»Ð¾Ñ‰Ð°Ð´ÑŒ Ñ€Ð°Ð¹Ð¾Ð½Ð°: [39m[38;5;132;01m{[39;00m[43marea_district[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;132;01m}[39;00m[38;5;124m Ð¼Â²[39m[38;5;124m"[39m)

[0;31mTypeError[0m: 'ellipsis' object is not subscriptable
TypeError: 'ellipsis' object is not subscriptable

